version: "2"
services:

  mysql:
    build: ./conf/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    volumes:
      - db:/var/lib/mysql

  apache-php:
    build: ./conf/apache-php
    ports:
      - '12345:80'
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PHP_UPLOAD_MAX_FILESIZE=100M
    restart: always
    ports:
      - 12346:80
    volumes:
      - pma-sessions:/sessions
    links:
      - mysql:db

volumes:
  db:
  pma-sessions:
